using System.IO;
using System.Globalization;
using System.Text;
using SNAPPY.CCTV.DiskCalculator.Models;

namespace SNAPPY.CCTV.DiskCalculator.Services;

/// <summary>
/// Creates a self-contained PDF report without requiring an external PDF package.
/// The report intentionally uses ASCII text so it renders reliably with the built-in Helvetica font.
/// </summary>
public static class PdfExportService
{
    public static void Export(
        string filePath,
        CalculatorResult result,
        VmsStorageResult? vms,
        IReadOnlyDictionary<string, string> inputs)
    {
        var lines = new List<string>
        {
            "SNAPPY CCTV DISK CALCULATOR - TOTAL RESULT",
            $"Report Date: {DateTime.Now:yyyy-MM-dd HH:mm:ss}",
            "",
            "CALCULATION INPUTS",
            "Camera Count: " + Get(inputs, "Camera Count"),
            "Encoding: " + Get(inputs, "Encoding"),
            "Resolution: " + Get(inputs, "Resolution"),
            "Frame Rate: " + Get(inputs, "Frame Rate"),
            "Bitrate Type: " + Get(inputs, "Bitrate Type"),
            "VBR Level: " + Get(inputs, "VBR Level"),
            "Scene Complexity: " + Get(inputs, "Scene Complexity"),
            "Calculation Mode: " + result.CalculationMode,
            "Bitrate Used: " + FormatKbps(result.StorageBitrateKbps),
            "Recording Hours / Day: " + Get(inputs, "Recording Hours"),
            "Retention: " + Get(inputs, "Retention"),
            "Storage Disk Size: " + Get(inputs, "Disk Size"),
            "Storage Overhead: " + Get(inputs, "Storage Overhead"),
            "",
            "STORAGE CALCULATION RESULT",
            $"Recommended Bitrate: {FormatKbps(result.RecommendedBitrateKbps)}",
            $"Estimated Average Bitrate: {FormatKbps(result.EstimatedAverageBitrateKbps)}",
            $"Storage Bitrate: {FormatKbps(result.StorageBitrateKbps)}",
            $"Per Camera / Day: {result.PerCameraDayGb:N2} GB",
            $"All Cameras / Day: {result.AllCamerasDayGb:N2} GB",
            $"Raw Storage: {result.RawStorageGb:N2} GB",
            $"Required Storage: {result.RequiredStorageGb:N2} GB",
            $"Required Storage: {result.RequiredStorageTb:N2} TB",
            $"Base Disk Count: {result.DiskCount:N0}",
            $"Retention Days: {result.RetentionDays:N0}",
            "",
            "VMS STORAGE / RAID RESULT"
        };

        if (vms is null)
        {
            lines.Add("VMS Mode: Not selected / not calculated");
        }
        else
        {
            lines.Add($"Storage Bay Type: {vms.BayType}");
            lines.Add($"RAID System: {vms.RaidType}");
            lines.Add($"Required Usable Storage: {vms.RequiredUsableTb:N2} TB");
            lines.Add($"Disk Size: {vms.DiskSizeTb:N0} TB / disk");
            lines.Add($"RAID Groups: {vms.RaidGroupCount:N0}");
            lines.Add($"Data Disks / RAID Group: {vms.DisksPerRaidGroup:N0}");
            lines.Add($"Required Data Disks: {vms.RequiredDiskCount:N0}");
            lines.Add($"Hot Spare Disks: {vms.HotSpareCount:N0}");
            lines.Add($"Total Installed Disks: {vms.TotalInstalledDiskCount:N0}");
            lines.Add($"Raw Data-Disk Capacity: {vms.RawCapacityTb:N2} TB");
            lines.Add($"RAID Usable Capacity: {vms.UsableCapacityTb:N2} TB");
            lines.Add($"Unused Usable Capacity: {vms.UnusedUsableTb:N2} TB");
            lines.Add($"Storage Devices Required: {vms.StorageDeviceCount:N0}");
            lines.Add($"Storage Device Type: {vms.StorageDeviceSummary}");
            lines.Add($"Total Available Bays: {vms.TotalBayCapacity:N0}");
            lines.Add($"Free Bays Across Devices: {vms.FreeBaysAcrossDevices:N0}");
            lines.Add($"RAID Status: {(vms.FitsInBays ? "Fits in 1 device" : $"Requires {vms.StorageDeviceCount} devices")}");
            lines.Add($"Capacity Formula: {vms.CapacityFormula}");
            lines.Add($"Fault Tolerance: {vms.FaultTolerance}");
            lines.Add($"Status: {vms.StatusText}");
        }

        lines.Add("");
        lines.Add("CALCULATION NOTE");
        lines.Add(result.CalculationNote);
        lines.Add("");
        lines.Add("Generated by SNAPPY CCTV Disk Calculator");

        SimplePdfWriter.Write(filePath, lines);
    }

    private static string Get(IReadOnlyDictionary<string, string> values, string key)
        => values.TryGetValue(key, out var value) ? value : "-";

    private static string FormatKbps(double kbps)
        => kbps >= 1000
            ? $"{kbps / 1000d:0.00} Mbps ({kbps:N0} Kbps)"
            : $"{kbps:N0} Kbps";

    private static class SimplePdfWriter
    {
        private const double PageWidth = 595;
        private const double PageHeight = 842;
        private const double Left = 42;
        private const double Top = 800;
        private const double Bottom = 42;
        private const double LineHeight = 15;

        public static void Write(string filePath, IReadOnlyList<string> sourceLines)
        {
            var lines = PrepareLines(sourceLines);
            int linesPerPage = (int)Math.Floor((Top - Bottom - 35) / LineHeight);
            int pageCount = Math.Max(1, (int)Math.Ceiling(lines.Count / (double)linesPerPage));

            var objects = new List<string>();
            objects.Add("<< /Type /Catalog /Pages 2 0 R >>");

            var pageObjectNumbers = new List<int>();
            var contentObjectNumbers = new List<int>();
            int nextObject = 4;
            for (int i = 0; i < pageCount; i++)
            {
                pageObjectNumbers.Add(nextObject++);
                contentObjectNumbers.Add(nextObject++);
            }

            objects.Add($"<< /Type /Pages /Kids [{string.Join(" ", pageObjectNumbers.Select(n => $"{n} 0 R"))}] /Count {pageCount} >>");
            objects.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");

            for (int pageIndex = 0; pageIndex < pageCount; pageIndex++)
            {
                var pageLines = lines.Skip(pageIndex * linesPerPage).Take(linesPerPage).ToList();
                string stream = BuildPageStream(pageLines, pageIndex + 1, pageCount);
                objects.Add($"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {PageWidth.ToString(CultureInfo.InvariantCulture)} {PageHeight.ToString(CultureInfo.InvariantCulture)}] /Resources << /Font << /F1 3 0 R >> >> /Contents {contentObjectNumbers[pageIndex]} 0 R >>");
                objects.Add($"<< /Length {Encoding.ASCII.GetByteCount(stream)} >>\nstream\n{stream}endstream");
            }

            var pdf = new StringBuilder();
            pdf.Append("%PDF-1.4\n");
            pdf.Append("%SNAPPY\n");

            var offsets = new List<long> { 0 };
            for (int objectIndex = 0; objectIndex < objects.Count; objectIndex++)
            {
                string obj = objects[objectIndex];
                offsets.Add(Encoding.ASCII.GetByteCount(pdf.ToString()));
                pdf.Append(objectIndex + 1).Append(" 0 obj\n");
                pdf.Append(obj).Append("\nendobj\n");
            }

            long xrefOffset = Encoding.ASCII.GetByteCount(pdf.ToString());
            pdf.Append("xref\n");
            pdf.Append("0 ").Append(objects.Count + 1).Append("\n");
            pdf.Append("0000000000 65535 f \n");
            for (int i = 1; i <= objects.Count; i++)
                pdf.Append(offsets[i].ToString("D10", CultureInfo.InvariantCulture)).Append(" 00000 n \n");

            pdf.Append("trailer\n");
            pdf.Append($"<< /Size {objects.Count + 1} /Root 1 0 R >>\n");
            pdf.Append("startxref\n").Append(xrefOffset).Append("\n%%EOF\n");

            File.WriteAllBytes(filePath, Encoding.ASCII.GetBytes(pdf.ToString()));
        }

        private static List<string> PrepareLines(IReadOnlyList<string> sourceLines)
        {
            var result = new List<string>();
            foreach (string source in sourceLines)
            {
                string clean = ToAscii(source);
                if (clean.Length == 0)
                {
                    result.Add(string.Empty);
                    continue;
                }

                const int maxChars = 88;
                string remaining = clean;
                while (remaining.Length > maxChars)
                {
                    int split = remaining.LastIndexOf(' ', maxChars);
                    if (split < 20) split = maxChars;
                    result.Add(remaining[..split].TrimEnd());
                    remaining = remaining[split..].TrimStart();
                }
                result.Add(remaining);
            }
            return result;
        }

        private static string BuildPageStream(IReadOnlyList<string> lines, int pageNumber, int pageCount)
        {
            var sb = new StringBuilder();
            sb.Append("BT\n/F1 18 Tf\n");
            sb.Append("42 800 Td\n");
            sb.Append("(").Append(Escape(lines.FirstOrDefault() ?? "SNAPPY CCTV Disk Calculator")).Append(") Tj\n");
            sb.Append("0 -26 Td\n/F1 9 Tf\n");

            bool first = true;
            foreach (string line in lines.Skip(1))
            {
                if (first)
                    first = false;
                else
                    sb.Append("0 -15 Td\n");

                if (line.Length == 0)
                {
                    sb.Append("0 -7 Td\n");
                    continue;
                }

                if (line.EndsWith("RESULT", StringComparison.Ordinal) ||
                    line is "CALCULATION INPUTS" or "STORAGE CALCULATION RESULT" or "VMS STORAGE / RAID RESULT" or "CALCULATION NOTE")
                {
                    sb.Append("/F1 11 Tf\n");
                    sb.Append("(").Append(Escape(line)).Append(") Tj\n");
                    sb.Append("/F1 9 Tf\n");
                }
                else
                {
                    sb.Append("(").Append(Escape(line)).Append(") Tj\n");
                }
            }

            sb.Append("0 -15 Td\n/F1 8 Tf\n");
            sb.Append("(Page ").Append(pageNumber).Append(" of ").Append(pageCount).Append(") Tj\nET\n");
            return sb.ToString();
        }

        private static string Escape(string value)
            => value.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");

        private static string ToAscii(string value)
        {
            var sb = new StringBuilder(value.Length);
            foreach (char c in value)
            {
                if (c <= 127)
                    sb.Append(c);
                else if (c is '\u2013' or '\u2014' or '\u2212')
                    sb.Append('-');
                else if (c is '\u00D7')
                    sb.Append('x');
                else if (c is '\u2022')
                    sb.Append('-');
                else
                    sb.Append('?');
            }
            return sb.ToString();
        }
    }
}
